import json, re
from dataclasses import dataclass
from .manager import AIProviderManager
from .model_catalog import split_model_key

@dataclass
class FixPlan:
    model: str
    reason: str
    files: list
    explanation: str

class AIFixOrchestrator:
    """Runs Head AI -> specialist fixer -> structured file changes."""
    def __init__(self, manager: AIProviderManager):
        self.manager = manager

    async def create_plan(self, error, files, *, progress=None, progress_base=0, progress_span=30, selected_model='auto'):
        if progress:
            progress.head_model = self.manager.head_model
            await progress.update(progress_base + 3, 'Head AI: analyzing the failed workflow…')
        if selected_model and selected_model != 'auto':
            if not self.manager.is_configured(selected_model):
                raise RuntimeError(f'Selected AI model is not configured: {selected_model}')
            chosen, reason = selected_model, 'Manually selected by user'
        else:
            chosen, reason = await self.manager.choose_fixer(error)
        pool=[chosen]+[m for m in self.manager.available_models() if '::' in m and m != chosen and m.split('::',1)[1] != self.manager.head_model]
        last=None
        for model in pool:
            if progress:
                progress.fixer_provider = self.manager.provider_name(model)
                _, display_model = split_model_key(model)
                await progress.update(progress_base + 9, f'Head AI selected {self.manager.provider_name(model)} specialist for this failure.', model=display_model)
            prompt=self._fix_prompt(error, files)
            if progress:
                _, display_model = split_model_key(model)
                await progress.update(progress_base + 16, 'Reading the repository snapshot and preparing the fix…', model=display_model)
            try:
                raw=await self.manager.ask_model(model,prompt,system=(
                    'You are Gitofy Fixer AI. Inspect the supplied repository snapshot and build failure. '
                    'Only propose concrete changes needed to make the failing workflow pass. Never invent files. '
                    'Return strict JSON with explanation and changes [{path,content,reason}].'
                ))
                data=self._parse(raw)
                changes=data.get('changes') or []
                valid=[c for c in changes if isinstance(c,dict) and c.get('path') in files and isinstance(c.get('content'),str)]
                if valid or not changes:
                    return FixPlan(split_model_key(model)[1],reason,valid,str(data.get('explanation') or 'Fix generated by specialist AI.'))
                last=RuntimeError('Fixer returned changes for files outside the repository snapshot')
            except Exception as exc:
                last=exc
                if progress: await progress.update(progress_base + 18, f'{split_model_key(model)[1]} was unavailable; trying the next specialist…', model=split_model_key(model)[1])
        raise RuntimeError(f'All selected fixer models failed: {last}')

    @staticmethod
    def _fix_prompt(error, files):
        # The complete tree is represented in the prompt, while binary/oversize files are excluded upstream.
        chunks = []
        for path, content in files.items():
            chunks.append(f'===== FILE: {path} =====\n{content[:50000]}')
        return f'FAILED WORKFLOW LOG:\n{error[:30000]}\n\nREPOSITORY FILES:\n' + '\n\n'.join(chunks)

    @staticmethod
    def _parse(raw):
        text = raw.strip()
        text = re.sub(r'^```(?:json)?\s*|\s*```$', '', text, flags=re.I|re.S)
        try:
            return json.loads(text)
        except json.JSONDecodeError:
            start, end = text.find('{'), text.rfind('}')
            if start >= 0 and end > start:
                return json.loads(text[start:end+1])
            raise
